### ISSUE TITLE
Hydration node mismatch warning upon installation

### ISSUE THREAD

**Issue by jocsonlouie** [modbender/nuxt-snackbar#10]
Hi! For some reason, when I installed this on my project, I got a lot of these Vue Warning messages. The warnings only appear if I install this repo. I'm wondering if you might know the solution. I'm using nuxt 3 and vuetify 3 btw. Thanks!
<img width="1189" alt="image" src="https://github.com/modbender/nuxt-snackbar/assets/65844045/8e8ba4a4-8f6d-4451-befa-521e1276bc05">

**Comment by modbender** [comment]
Hey @jocsonlouie
The error doesn't seem to be coming from Snackbar. 
Because if it was, then `NuxtSnackbar` would have been one of the elements shown in that list.

In the Hydration message it clearly says
`Client vnode: input`

**Comment by jocsonlouie** [comment]
That's really weird because when I remove the Snackbar repo, the warnings disappear. I'll keep investigating to see what's causing this behavior. Thanks a lot for your help!
