### ISSUE TITLE
Vue3 snackbar memory leak

### ISSUE THREAD

**Issue by FamilyMan** [modbender/nuxt-snackbar#17]
There is an issue with vue3-snackbar above v2.2.0
I have reported the issue here: https://github.com/evo-mark/vue3-snackbar/issues/12
So you should pin the version by adding:

"vue3-snackbar": "2.2.0"

to your package.json

**Comment by modbender** [comment]
Alright, I had to reset my PC so will soon start working on this.

**Comment by modbender** [comment]
Fixed in latest v1.1.0 update
