### ISSUE TITLE
nvalid prop type check failed for prop "iconPresets"

### ISSUE THREAD

**Issue by frederic117** [modbender/nuxt-snackbar#18]
We encountered a Vue warning indicating an invalid prop type check failure for the prop "iconPresets". The warning message specifies that an Object was expected, but Null was received.

Error Details:

typescript
[Vue warn]: Invalid prop: type check failed for prop "iconPresets". Expected Object, got Null  
  at <Vue3SnackbarMessage key=1 message= 
    {type: 'success', text: 'xxxxxx', dismissible: false, group: '3b85d1e2', duration: 5000, …}
    message-class=""  ... > 
  at <TransitionGroup name="vue3-snackbar-message" tag="div" class="vue3-snackbar--messages" > 
  at <Vue3Snackbar top=true bottom=true left=false  ... > 
  at <NuxtSnackbar> 
  at <ClientOnly> 
  at <App key=4 > 
  at <NuxtRoot>
Promise.then (async)		
confirmAddnoteBene @ ModalNoteBene.vue:167
Show 27 more frames
Steps to Reproduce:

Trigger the addition of a note in the application.
Observe the console for Vue warnings.
Expected Behavior:
The "iconPresets" prop should receive a valid Object type to avoid type check warnings.

Actual Behavior:
The "iconPresets" prop receives a Null value, causing a Vue warning about the invalid prop type.

Additional Context:
This issue occurs when adding a note and the success message is displayed using the Vue3SnackbarMessage component.

Possible Solution:
Ensure that the "iconPresets" prop is always provided with a valid Object type, or handle the scenario where it might be Null.

Thanks a lot for your help

**Comment by ijshd7** [comment]
Bumping because I am seeing this warning appear as well.

after installing I looked at node_modules/nuxt-snackbar/dist/module.d.ts and only see these properties included:

    top: boolean;
    bottom: boolean;
    left: boolean;
    right: boolean;
    groups: boolean;
    success: string;
    error: string;
    warning: string;
    info: string;
    duration: number;
    messageClass: string;
    zIndex: number;
    dense: boolean;
    shadow: boolean;
    reverse: boolean;
    border: string;
    backgroundOpacity: number;
    backgroundColor: string;
    baseBackgroundColor: string;

**Comment by modbender** [comment]
Fixed in latest v1.1.0 update
