### ISSUE TITLE
Support for layouts

### ISSUE THREAD

**Issue by kennedyngigi4** [modbender/nuxt-snackbar#2]
How can one get the snackbar usable within the layouts>default.vue file??

I have seen it can only be supported in app.vue.

**Comment by modbender** [comment]
Sure it can be added to layouts > `default.vue`

In fact that's how I use it in my project. It's just not documented since I thought it was unnecessary to mention the obvious.

This is how I'm using it in my code:
```vue
<template>
  <NavBar>
    <slot />
  </NavBar>
  <NuxtSnackbar />
</template>
```

Just remember to keep `NuxtSnackbar` tag last, like above.

**Comment by modbender** [comment]
@kennedyngigi4 closing it as completed.
