### ISSUE TITLE
Error: No Snackbar provided!

### ISSUE THREAD

**Issue by autorunman22** [modbender/nuxt-snackbar#4]
I wrap the snackbar calls to simple composable so that I can reduce boilerplate:

`composables/useToast.js`
```
export const useToast = (type: string = "success", title: string = "", text: string) => {
    const snackbar = useSnackbar();
    
    snackbar.add({
        type: type,
        title: title,
        text: text
    })
}
```

But when I refresh the page, i'm getting this error:
```
Uncaught (in promise) Error: No Snackbar provided!
    at be (vue3-snackbar.js?v=80f43774:407:11)
    at useToast (useToast.ts:3:5)
```

**Comment by modbender** [comment]
For now as I see it, it won't work because the `useSnackbar` needs to be called inside `setup`. I'll check more on it.
@craigrileyuk if you could help out...

**Comment by AnttiMJohansson** [comment]
I've followed the steps from readme and end up with same error: Uncaught Error: No Snackbar provided!

In my case the <NuxtSnackbar /> gets highlighted as not recognized: 
(property) NuxtSnackbar: typeof _default
Type '{}' is not assignable to type 'ComponentProps<typeof _default>'.
  Type '{}' is missing the following properties from type 'typeof _default': render, injectts(2322)

**Comment by AnttiMJohansson** [comment]
Sorry the code that gets highlighted got dropped from message. 

`<NuxtSnackbar />`

**Comment by craigrileyuk** [comment]
@autorunman22 

Inside your `useToast` composable, try wrapping your main function in an `onMounted` a la

```js
onMounted(() => {
    snackbar.add({
        type,
        title,
        text,
    });
});
```

I've used the exact same setup as this and it's working in my test app.

**Comment by autorunman22** [comment]
I can confirm that its working. Thank you @craigrileyuk
