### ISSUE TITLE
Install error: Cannot read properties of null (reading 'edgesOut')

### ISSUE THREAD

**Issue by davestewart** [modbender/nuxt-snackbar#5]
Hey!

Git cloned your module and ran `npm install` and got this error:

```
npm ERR! Cannot read properties of null (reading 'edgesOut')
```

Any ideas?

**Comment by davestewart** [comment]
Strangely `yarn install` worked fine.

I Googled the error, and apparently it could be something to do with non-English characters?

**Comment by modbender** [comment]
I think it's probably got to do with lock file. So it's working fine now?

I'm thinking of switching to pnpm

**Comment by davestewart** [comment]
Yup! I could develop and build just fine. Might be worth adding to docs though.

**Comment by modbender** [comment]
Done
