### ISSUE TITLE
Not working without refresh the page

### ISSUE THREAD

**Issue by rashidpathiyil** [modbender/nuxt-snackbar#9]
It's only working after hard refresh the page

**Comment by rashidpathiyil** [comment]
It's fixed after moving the Snackbar Component from Layout to app.vue, not working properly if placed inside Layouts

`
<template>
  <main>
    Main Content
  </main>
  <NuxtSnackbar />
</template>
`

Nuxt: 3.6.2

**Comment by modbender** [comment]
Yeah I guess that Readme update is misleading. By default add it to `app.vue`. If you are facing problems then try using it in `layouts.vue`
